BEGIN TRANSACTION;

CREATE TABLE zoos (
  id integer PRIMARY KEY AUTOINCREMENT,
  name text NOT NULL UNIQUE
);

CREATE TABLE bears (
  id integer PRIMARY KEY AUTOINCREMENT,
  name text NOT NULL UNIQUE
);

COMMIT TRANSACTION;
